server:
  port: 8801
logging:
  level:
    ROOT: INFO
    io.github.jhipster: INFO
    com.ecidi.uaa: INFO

spring:
  profiles:
    active: dev
    include:
      - swagger
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://42.49.141.68:3306/microservice_uaa?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: admin123..
    hikari:
      auto-commit: false

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
  #            hibernate.cache.use_second_level_cache: true
  #            hibernate.cache.use_query_cache: false
  #            hibernate.generate_statistics: true
  #            hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
  #            hibernate.cache.hazelcast.instance_name: uaa
  #            hibernate.cache.use_minimal_puts: true
  #            hibernate.cache.hazelcast.use_lite_member: true
  liquibase:
    contexts: dev
